version: '3'
services:
  handler:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - SQLITE_DB_PATH=/data/app.db
    volumes:
      - ./data:/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    ports:
      - "6379:6379"